---

# Provision abenteuerritter.de website
# ansible-playbook -i abenteuerritter.de, provision.yml

- hosts: abenteuerritter.de
  become: yes
  vars:
    packages:
      - curl
      - software-properties-common
      - python-software-properties
      - python-apt
      - python-pycurl
      - apt-transport-https
      - ca-certificates
      - nginx
      - rsync
  tasks:
    - apt: update_cache=yes upgrade=dist cache_valid_time=3600
    - apt: name={{ item }} state=latest
      with_items: "{{ packages }}"
    - file: path=/srv/www/abenteuerritter.de state=directory
    - file: path=/etc/nginx/sites-enabled/default state=absent
    - copy:
        content: >
          server {
              listen 80;
              root /srv/www/abenteuerritter.de;

              access_log /var/log/nginx/abenteuerritter-access.log;
              error_log /var/log/nginx/abenteuerritter-error.log;

              location / {
                  index index.html;
              }
          }
        dest: /etc/nginx/sites-enabled/{{ ansible_hostname }}.conf
    - service: name=nginx state=started enabled=yes
    - service: name=nginx state=restarted
